# Generated by Django 3.2.7 on 2021-09-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='countInStock',
        ),
    ]
